name: CI
on: 
  workflow_dispatch:
  pull_request:
  push:
    branches: 
      - master
    paths-ignore:
      - '.github/**'
      - '!.github/workflows/main.yml'
      - 'docs/**'
      - '*.md'
      - '.git*'

jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.8, 3.9]
        poetry-version: [1.0, 1.1.4]
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run image
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: ${{ matrix.poetry-version }}
      - name: Install libraries
        run: poetry install 
  test:
    needs: ci
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Test coverage
        run: poetry pytest --cov=./ --cov-report=xml
      - name: Upload coverage to Codecov
      - uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml
          flags: unittests
          env_vars: OS,PYTHON
          fail_ci_if_error: true
          verbose: true
            
            
            
  
